export type Verse = {
  ref: string;
  text: string;
};

export const VERSES: Verse[] = [
  { ref: "1 Corinthians 10:13", text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it." },
  { ref: "1 Corinthians 6:18", text: "Flee from sexual immorality. All other sins a person commits are outside the body, but whoever sins sexually, sins against their own body." },
  { ref: "2 Timothy 2:22", text: "Flee the evil desires of youth and pursue righteousness, faith, love and peace, along with those who call on the Lord out of a pure heart." },
  { ref: "James 1:12", text: "Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life that the Lord has promised to those who love him." },
  { ref: "James 1:14-15", text: "But each person is tempted when they are dragged away by their own evil desire and enticed. Then, after desire has conceived, it gives birth to sin; and sin, when it is full-grown, gives birth to death." },
  { ref: "Romans 12:2", text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God’s will is — his good, pleasing and perfect will." },
  { ref: "Philippians 4:13", text: "I can do all this through him who gives me strength." },
  { ref: "2 Corinthians 12:9", text: "But he said to me, ‘My grace is sufficient for you, for my power is made perfect in weakness.’ Therefore I will boast all the more gladly about my weaknesses, so that Christ’s power may rest on me." },
  { ref: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law." },
  { ref: "Galatians 5:16", text: "So I say, walk by the Spirit, and you will not gratify the desires of the flesh." },
  { ref: "Matthew 5:28", text: "But I tell you that anyone who looks at a woman lustfully has already committed adultery with her in his heart." },
  { ref: "Matthew 26:41", text: "Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak." },
  { ref: "Job 31:1", text: "I made a covenant with my eyes not to look lustfully at a young woman." },
  { ref: "Psalm 119:9", text: "How can a young person stay on the path of purity? By living according to your word." },
  { ref: "Psalm 119:11", text: "I have hidden your word in my heart that I might not sin against you." },
  { ref: "Proverbs 4:23", text: "Above all else, guard your heart, for everything you do flows from it." },
  { ref: "Proverbs 5:21", text: "For your ways are in full view of the Lord, and he examines all your paths." },
  { ref: "Proverbs 6:25", text: "Do not lust in your heart after her beauty or let her captivate you with her eyes." },
  { ref: "Proverbs 6:27", text: "Can a man scoop fire into his lap without his clothes being burned?" },
  { ref: "Proverbs 25:28", text: "Like a city whose walls are broken through is a person who lacks self-control." },
  { ref: "Proverbs 16:32", text: "Better a patient person than a warrior, one with self-control than one who takes a city." },
  { ref: "Proverbs 28:13", text: "Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy." },
  { ref: "1 Peter 1:13-14", text: "Therefore, with minds that are alert and fully sober, set your hope on the grace to be brought to you when Jesus Christ is revealed at his coming. As obedient children, do not conform to the evil desires you had when you lived in ignorance." },
  { ref: "1 Peter 2:11", text: "Dear friends, I urge you, as foreigners and exiles, to abstain from sinful desires, which wage war against your soul." },
  { ref: "1 Peter 5:8", text: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour." },
  { ref: "1 Peter 5:10", text: "And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast." },
  { ref: "1 Thessalonians 4:3-4", text: "It is God’s will that you should be sanctified: that you should avoid sexual immorality; that each of you should learn to control your own body in a way that is holy and honorable." },
  { ref: "1 Thessalonians 5:23", text: "May God himself, the God of peace, sanctify you through and through. May your whole spirit, soul and body be kept blameless at the coming of our Lord Jesus Christ." },
  { ref: "Ephesians 4:22-24", text: "You were taught, with regard to your former way of life, to put off your old self, which is being corrupted by its deceitful desires; to be made new in the attitude of your minds; and to put on the new self, created to be like God in true righteousness and holiness." },
  { ref: "Ephesians 5:3", text: "But among you there must not be even a hint of sexual immorality, or of any kind of impurity, or of greed, because these are improper for God’s holy people." },
  { ref: "Ephesians 6:10-11", text: "Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil’s schemes." },
  { ref: "Romans 6:12", text: "Therefore do not let sin reign in your mortal body so that you obey its evil desires." },
  { ref: "Romans 6:14", text: "For sin shall no longer be your master, because you are not under the law, but under grace." },
  { ref: "Romans 8:1", text: "Therefore, there is now no condemnation for those who are in Christ Jesus." },
  { ref: "Romans 8:5-6", text: "Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires. The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace." },
  { ref: "Romans 8:13", text: "For if you live according to the flesh, you will die; but if by the Spirit you put to death the misdeeds of the body, you will live." },
  { ref: "Romans 13:14", text: "Rather, clothe yourselves with the Lord Jesus Christ, and do not think about how to gratify the desires of the flesh." },
  { ref: "Colossians 3:2", text: "Set your minds on things above, not on earthly things." },
  { ref: "Colossians 3:5", text: "Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed, which is idolatry." },
  { ref: "Colossians 3:10", text: "And have put on the new self, which is being renewed in knowledge in the image of its Creator." },
  { ref: "Hebrews 4:15-16", text: "For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are — yet he did not sin. Let us then approach God’s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need." },
  { ref: "Hebrews 12:1-2", text: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us, fixing our eyes on Jesus, the pioneer and perfecter of faith." },
  { ref: "Hebrews 12:11", text: "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it." },
  { ref: "Hebrews 13:5-6", text: "Keep your lives free from the love of money and be content with what you have, because God has said, ‘Never will I leave you; never will I forsake you.’" },
  { ref: "James 1:2-4", text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything." },
  { ref: "James 4:7", text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you." },
  { ref: "James 4:8", text: "Come near to God and he will come near to you. Wash your hands, you sinners, and purify your hearts, you double-minded." },
  { ref: "Psalm 1:1-2", text: "Blessed is the one who does not walk in step with the wicked or stand in the way that sinners take or sit in the company of mockers, but whose delight is in the law of the Lord, and who meditates on his law day and night." },
  { ref: "Psalm 23:4", text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation — whom shall I fear? The Lord is the stronghold of my life — of whom shall I be afraid?" },
  { ref: "Psalm 28:7", text: "The Lord is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him." },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you." },
  { ref: "Psalm 34:17-18", text: "The righteous cry out, and the Lord hears them; he delivers them from all their troubles. The Lord is close to the brokenhearted and saves those who are crushed in spirit." },
  { ref: "Psalm 37:23-24", text: "The Lord makes firm the steps of the one who delights in him; though he may stumble, he will not fall, for the Lord upholds him with his hand." },
  { ref: "Psalm 40:1-2", text: "I waited patiently for the Lord; he turned to me and heard my cry. He lifted me out of the slimy pit, out of the mud and mire; he set my feet on a rock and gave me a firm place to stand." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in trouble." },
  { ref: "Psalm 51:10", text: "Create in me a pure heart, O God, and renew a steadfast spirit within me." },
  { ref: "Psalm 51:12", text: "Restore to me the joy of your salvation and grant me a willing spirit, to sustain me." },
  { ref: "Psalm 73:26", text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever." },
  { ref: "Psalm 91:1-2", text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the Lord, ‘He is my refuge and my fortress, my God, in whom I trust.’" },
  { ref: "Psalm 103:12", text: "As far as the east is from the west, so far has he removed our transgressions from us." },
  { ref: "Psalm 121:1-2", text: "I lift up my eyes to the mountains — where does my help come from? My help comes from the Lord, the Maker of heaven and earth." },
  { ref: "Psalm 139:23-24", text: "Search me, God, and know my heart; test me and know my anxious thoughts. See if there is any offensive way in me, and lead me in the way everlasting." },
  { ref: "Isaiah 40:29", text: "He gives strength to the weary and increases the power of the weak." },
  { ref: "Isaiah 40:31", text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." },
  { ref: "Isaiah 41:10", text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand." },
  { ref: "Isaiah 43:18-19", text: "Forget the former things; do not dwell on the past. See, I am doing a new thing! Now it springs up; do you not perceive it?" },
  { ref: "Jeremiah 17:9-10", text: "The heart is deceitful above all things and beyond cure. Who can understand it? ‘I the Lord search the heart and examine the mind, to reward each person according to their conduct, according to what their deeds deserve.’" },
  { ref: "Jeremiah 29:11", text: "‘For I know the plans I have for you,’ declares the Lord, ‘plans to prosper you and not to harm you, plans to give you hope and a future.’" },
  { ref: "Lamentations 3:22-23", text: "Because of the Lord’s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness." },
  { ref: "Ezekiel 36:26", text: "I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh." },
  { ref: "Micah 7:8", text: "Do not gloat over me, my enemy! Though I have fallen, I will rise. Though I sit in darkness, the Lord will be my light." },
  { ref: "Zephaniah 3:17", text: "The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing." },
  { ref: "Matthew 4:10", text: "Jesus said to him, ‘Away from me, Satan! For it is written: “Worship the Lord your God, and serve him only.”’" },
  { ref: "Matthew 5:8", text: "Blessed are the pure in heart, for they will see God." },
  { ref: "Matthew 6:13", text: "And lead us not into temptation, but deliver us from the evil one." },
  { ref: "Matthew 11:28-30", text: "Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light." },
  { ref: "Mark 14:38", text: "Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak." },
  { ref: "Luke 4:8", text: "Jesus answered, ‘It is written: “Worship the Lord your God and serve him only.”’" },
  { ref: "Luke 22:40", text: "On reaching the place, he said to them, ‘Pray that you will not fall into temptation.’" },
  { ref: "John 8:11", text: "‘Then neither do I condemn you,’ Jesus declared. ‘Go now and leave your life of sin.’" },
  { ref: "John 8:32", text: "Then you will know the truth, and the truth will set you free." },
  { ref: "John 8:36", text: "So if the Son sets you free, you will be free indeed." },
  { ref: "John 14:27", text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid." },
  { ref: "John 15:5", text: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing." },
  { ref: "John 16:33", text: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world." },
  { ref: "Acts 3:19", text: "Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord." },
  { ref: "Romans 5:3-5", text: "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope. And hope does not put us to shame, because God’s love has been poured out into our hearts through the Holy Spirit, who has been given to us." },
  { ref: "Romans 7:24-25", text: "What a wretched man I am! Who will rescue me from this body that is subject to death? Thanks be to God, who delivers me through Jesus Christ our Lord!" },
  { ref: "Romans 12:1", text: "Therefore, I urge you, brothers and sisters, in view of God’s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God — this is your true and proper worship." },
  { ref: "Romans 12:21", text: "Do not be overcome by evil, but overcome evil with good." },
  { ref: "1 Corinthians 6:19-20", text: "Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price. Therefore honor God with your bodies." },
  { ref: "1 Corinthians 9:27", text: "No, I strike a blow to my body and make it my slave so that after I have preached to others, I myself will not be disqualified for the prize." },
  { ref: "1 Corinthians 15:57-58", text: "But thanks be to God! He gives us the victory through our Lord Jesus Christ. Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain." },
  { ref: "2 Corinthians 4:16-17", text: "Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day. For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all." },
  { ref: "2 Corinthians 5:17", text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!" },
  { ref: "2 Corinthians 10:5", text: "We demolish arguments and every pretension that sets itself up against the knowledge of God, and we take captive every thought to make it obedient to Christ." },
  { ref: "Galatians 2:20", text: "I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me." },
  { ref: "Galatians 6:9", text: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up." },
  { ref: "Ephesians 3:16", text: "I pray that out of his glorious riches he may strengthen you with power through his Spirit in your inner being." },
  { ref: "Ephesians 4:1", text: "As a prisoner for the Lord, then, I urge you to live a life worthy of the calling you have received." },
  { ref: "Ephesians 6:13", text: "Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand." },
  { ref: "Philippians 1:6", text: "Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus." },
  { ref: "Philippians 3:13-14", text: "Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus." },
  { ref: "Philippians 4:6-7", text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus." },
  { ref: "Philippians 4:8", text: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable — if anything is excellent or praiseworthy — think about such things." },
  { ref: "Colossians 1:11", text: "Being strengthened with all power according to his glorious might so that you may have great endurance and patience." },
  { ref: "Colossians 3:1-2", text: "Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God. Set your minds on things above, not on earthly things." },
  { ref: "1 Thessalonians 5:21-22", text: "But test them all; hold on to what is good, reject every kind of evil." },
  { ref: "2 Thessalonians 3:3", text: "But the Lord is faithful, and he will strengthen you and protect you from the evil one." },
  { ref: "1 Timothy 6:11-12", text: "But you, man of God, flee from all this, and pursue righteousness, godliness, faith, love, endurance and gentleness. Fight the good fight of the faith. Take hold of the eternal life to which you were called." },
  { ref: "2 Timothy 1:7", text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline." },
  { ref: "2 Timothy 4:7", text: "I have fought the good fight, I have finished the race, I have kept the faith." },
  { ref: "Titus 2:11-12", text: "For the grace of God has appeared that offers salvation to all people. It teaches us to say ‘No’ to ungodliness and worldly passions, and to live self-controlled, upright and godly lives in this present age." },
  { ref: "Hebrews 2:18", text: "Because he himself suffered when he was tempted, he is able to help those who are being tempted." },
  { ref: "Hebrews 10:23", text: "Let us hold unswervingly to the hope we profess, for he who promised is faithful." },
  { ref: "Hebrews 11:1", text: "Now faith is confidence in what we hope for and assurance about what we do not see." },
  { ref: "Hebrews 12:7", text: "Endure hardship as discipline; God is treating you as his children. For what children are not disciplined by their father?" },
  { ref: "James 1:17", text: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows." },
  { ref: "James 5:16", text: "Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective." },
  { ref: "1 Peter 4:1-2", text: "Therefore, since Christ suffered in his body, arm yourselves also with the same attitude, because whoever suffers in the body is done with sin. As a result, they do not live the rest of their earthly lives for evil human desires, but rather for the will of God." },
  { ref: "2 Peter 1:5-7", text: "For this very reason, make every effort to add to your faith goodness; and to goodness, knowledge; and to knowledge, self-control; and to self-control, perseverance; and to perseverance, godliness; and to godliness, mutual affection; and to mutual affection, love." },
  { ref: "1 John 1:9", text: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness." },
  { ref: "1 John 2:16", text: "For everything in the world — the lust of the flesh, the lust of the eyes, and the pride of life — comes not from the Father but from the world." },
  { ref: "1 John 4:4", text: "You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world." },
  { ref: "1 John 5:4", text: "For everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith." },
  { ref: "Revelation 3:21", text: "To the one who is victorious, I will give the right to sit with me on my throne, just as I was victorious and sat down with my Father on his throne." },
  { ref: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go." },
  { ref: "Deuteronomy 31:6", text: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you." },
];
